FarosFront/Faros.FrontEnd/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Faros.FrontEnd.Controllers
{
    public class AlbumController : Controller
    {
        public IActionResult AlbumHome()
        {
            return View();
        }
    }
}

FarosFront/Faros.FrontEnd/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Faros.FrontEnd.Controllers
{
    public class BlogController : Controller
    {
        public BlogController()
        {

        }
        public IActionResult BlogHome()
        {
            return View();
        }
      
    }
}

FarosFront/Faros.FrontEnd/Controllers/CarrousselEditController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Core.Common;
using Faros.Common;
using Faros.Common.Constants;
using Faros.Common.Helpers;
//using Faros.FrontEnd.Models;
using Faros.FrontEnd.Proxy;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace Faros.FrontEnd.Controllers
{
    public class CarrousselEditController : Controller
    {

        public static List<Arquivo> lstArquivos;
        private ArquivoProxy _servicoImagem;
        private string _imagePath;
        IConfiguration _configurationOutPut;
        IHostingEnvironment _appEnviroment;

        public CarrousselEditController(IConfiguration configurationInput,
                                        IHostingEnvironment environment)

        {
            _configurationOutPut = configurationInput;
            _appEnviroment = environment;
            _imagePath = _appEnviroment.ContentRootPath + AssemblyConstants.GetPathImageByBuild(FileConstants.DEV,AssemblyConstants.PATH_IMAGE_INDEX_CARROUSSEL);
            _servicoImagem = new ArquivoProxy(_configurationOutPut.GetValue<string>("UriHost"));
        }
        public IActionResult CarrousselHome()
        {
            return View();
        }

        [HttpPost]//Colocar o post pois será passado a lista no retorno
        public IActionResult CarrousselHome(IEnumerable<Arquivo> arquivos)
        {
            return View(arquivos);
        }


        //Recebe uma lista de arquivos vindas do front usando sempre a entidade IFormFile 

        [HttpPost]
        public IActionResult UploadImagem(IList<IFormFile> arquivos)
        {

            lstArquivos = new List<Arquivo>();
            if (arquivos.Count() > 0)
            {

                int i = 0;
                MemoryStream ms;
                

                arquivos.ToList().ForEach(x =>
                {

                    //cria um memory stream para gravar os arquivos
                    ms = new MemoryStream();
                    //lê os bytes do arquivo e o copia dentro da memoryStream
                    x.OpenReadStream().CopyTo(ms);

                    lstArquivos.Add(

                        new Arquivo()
                        {
                            ContentType = x.ContentType,
                            Posicao = i++,
                            Nome = "panel_" + i.ToString(),
                            NomeSalvar = x.FileName,
                            Tamanho = "1500x500",
                            ArquivoArray = ms.ToArray()
                        });

                });

                
                ArquivoHelper.SalvarLstArquivos(lstArquivos, _imagePath);

                //Seta o path do arquivo de acordo com o caminho salvo
                SetFilesPath(lstArquivos, AssemblyConstants.GetPathImageByBuild(FileConstants.PROD,AssemblyConstants.PATH_IMAGE_INDEX_CARROUSSEL));

                _servicoImagem.PostListImagens(new List<Arquivo>(lstArquivos).Select(x=>new Arquivo() {
                    Id=x.Id,
                    ContentType=x.ContentType,
                    Nome=x.Nome,
                    NomeSalvar=x.NomeSalvar,
                    Path=x.Path,
                    Posicao=x.Posicao,
                    Tamanho=x.Tamanho
                }));


                return View("CarrousselHome", lstArquivos);

            }

            return View();
        }

        private void SetFilesPath(List<Arquivo> lstArquivos, string path)
        {
            lstArquivos
                    .ForEach(x =>
                    x.Path = ArquivoHelper.GetPathExetension(path, x.NomeSalvar, x.Nome));
        }

        [HttpGet]
        public FileStreamResult VerImagem(string nome)
        {
            var myArquivo = lstArquivos.Where(x => x.Nome == nome).FirstOrDefault();
            MemoryStream ms = new MemoryStream(myArquivo.ArquivoArray);
            return new FileStreamResult(ms, myArquivo.ContentType);
        }

        [HttpPost]
        public void PostArquivo(Arquivo arquivo)
        {
            var hehe = arquivo;
        }


    }
}

FarosFront/Faros.FrontEnd/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <base href="/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Faros D'Ajuda</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-inverse navbar-expand-lg navbar-light">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Blog" asp-action="BlogHome">Blog</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Faros na Web
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Contact">Contato</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="About">Sobre Nós</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Album" asp-action="AlbumHome">Álbum</a>
                            <a class="dropdown-item" asp-area="" asp-controller="CarrousselEdit" asp-action="CarrousselHome">Carroussel</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Blog" asp-action="BlogHome">Blog</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Admin</a>
                    </li>
                </ul>
                <!--<form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>-->
            </div>
        </nav>
    </header>
    <br />

    <body>

        @RenderBody()

    </body>
    <footer class="footer-colorful">
        <address>
            <strong>Faros D'Ajuda</strong> Rua Alziro de Oliveira 2800,Jd. Morumbi
            <br> Bragança Paulista,SP
            <br>
            <br>

            Email:abrigofrasodajuda@gmail.com
        </address>

    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://unpkg.com/popper.js"></script>
    <script src="https://unpkg.com/tooltip.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</body>
</html>